apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app.iot.deployment/name: app-one
  template:
    metadata:
      labels:
        app.iot.deployment/name: app-one
    spec:
      containers:
      - name: iot-app-one-c
        image: theterror/iot-app-one
        ports:
          - containerPort: 80
            name: http-port