apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: iot-ingress-route
spec:
  routes:
  - kind: Rule
    match: Host(`app1.com`) && PathPrefix(`/`)
    services:
    - kind: Service
      name: app-one
      port: iot-svc-port
  - kind: Rule
    match: Host(`app2.com`)  && PathPrefix(`/`)
    services:
    - kind: Service
      name: app-two
      port: iot-svc-port
  - kind: Rule
    match:  PathPrefix(`/`)
    services:
    - kind: Service
      name: app-three
      port: iot-svc-port
