# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_NODENAME 			= "jfayeS"
SERVER_ETH1_IP				= "192.168.56.110"
WORKER_NODE_NAME			= "jfayeSW"
WORKER_NODE_ETH1_IP			= "192.168.56.111"
RAM							= 1024
CPUs						= 2
K3S_PORT					= "6443"
K3S_TOKEN					= "42@ilove"
K3S_AGENT_TOKEN				= "42@ilove"
K3S_URL						= "https://" + SERVER_ETH1_IP + ":" + K3S_PORT
SERVER_NODE_HOME			= "/home/vagrant"

SERVER_NODE_ENV_VARIABLES	= {
	"SERVER_NODE_HOME" => SERVER_NODE_HOME,
	"SERVER_ETH1_IP" => SERVER_ETH1_IP,
	"K3S_TOKEN" => K3S_TOKEN,
	"K3S_AGENT_TOKEN" => K3S_AGENT_TOKEN,
}

WORKER_NODE_ENV_VARIABLES	= {
	"SERVER_NODE_HOME" => SERVER_NODE_HOME,
	"WORKER_NODE_ETH1_IP" => WORKER_NODE_ETH1_IP,
	"K3S_TOKEN" => K3S_TOKEN,
	"K3S_URL" => K3S_URL,
}

Vagrant.configure("2") do |config|

	config.vm.define SERVER_NODENAME do |server|

		server.vm.hostname = SERVER_NODENAME

		server.vm.box = "debian/bookworm64"

		server.vm.network "private_network", ip: SERVER_ETH1_IP

		server.vm.synced_folder ".", "/vagrant", disabled: true

		server.vm.provider "virtualbox" do |vb|
			vb.name = SERVER_NODENAME
			vb.memory = RAM
			vb.cpus = CPUs
		end

		server.vm.provision "shell", env: SERVER_NODE_ENV_VARIABLES, path: "./tools/server-node-script.sh"

	end


	config.vm.define WORKER_NODE_NAME do |server_worker|

		server_worker.vm.hostname = WORKER_NODE_NAME

		server_worker.vm.box = "debian/bookworm64"

		server_worker.vm.network "private_network", ip: WORKER_NODE_ETH1_IP

		server_worker.vm.synced_folder ".", "/vagrant", disabled: true

		server_worker.vm.provider "virtualbox" do |vb|
			vb.name = WORKER_NODE_NAME
			vb.memory = RAM
			vb.cpus = CPUs
		end

		server_worker.vm.provision "shell", env: WORKER_NODE_ENV_VARIABLES, path: "./tools/worker-node-script.sh"

	end
end
